# nixpacks.toml
[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = [
  "echo 'Installing dependencies...'",
  "npm ci --no-audit --no-fund",
  "echo 'Dependencies installed successfully'"
]

[phases.build]
cmds = [
  "echo 'Building application...'",
  "npm run build",
  "echo 'Verifying build output...'",
  "ls -la dist/",
  "echo 'Build verification complete'"
]

[start]
cmd = "npm run prestart && npm start"

[variables]
NODE_ENV = "production"
NPM_CONFIG_LOGLEVEL = "info"
