# railway.toml
[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 60
healthcheckInterval = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

# 必要な環境変数はRailway UIで設定
# GEMINI_API_KEY=your_gemini_api_key
# NOTION_TOKEN=your_notion_token  
# NOTION_DATABASE_ID=your_notion_database_id
